// @generated by scripts/generate-provider-sources.mjs — DO NOT EDIT.
// Provider 内置表数据段（contracts/providers.json 单一来源）。字段语义见
// provider_profiles.rs 的 ProviderProfileEntry 注释。

#![allow(dead_code)]

use crate::model_http::ModelApiFormat;
use crate::provider_profiles::{
    AuthKind, ProviderAuth, ProviderCapabilities, ProviderDefaultProfile, ProviderModelWire,
    ProviderProfileEntry,
};

pub(crate) const TIMEOUT_MIN_MS: u64 = 1_000;
pub(crate) const TIMEOUT_MAX_MS: u64 = 300_000;
pub(crate) const TIMEOUT_DEFAULT_MS: u64 = 60_000;
pub(crate) const MAX_OUTPUT_MIN: u64 = 1;
pub(crate) const MAX_OUTPUT_MAX: u64 = 512_000;
pub(crate) const MAX_OUTPUT_DEFAULT: u64 = 4_096;
pub(crate) const CONTEXT_MIN: u64 = 8_192;
pub(crate) const CONTEXT_MAX: u64 = 2_000_000;
pub(crate) const CONTEXT_DEFAULT: u64 = 128_000;
pub(crate) const IDENTIFIER_MAX_BYTES: usize = 128;
pub(crate) const ENDPOINT_MAX_BYTES: usize = 4_096;
pub(crate) const MODEL_ID_MAX_BYTES: usize = 256;

pub(crate) const CURRENT_PROVIDER_SECRET_PREFIXES: &[&str] = &[
    "provider.openai-compatible.api-key",
    "provider.custom-openai-compatible.api-key",
    "provider.openai-responses.api-key",
    "provider.generic-anthropic-compatible.api-key",
    "provider.custom-anthropic-compatible.api-key",
    "provider.zhipu-glm.api-key",
    "provider.deepseek.api-key",
    "provider.minimax-chat.api-key",
    "provider.gemini.api-key",
    "provider.kimi.api-key",
    "provider.kimi-coding.api-key",
    "provider.orcarouter.api-key",
    "provider.opencode-go.api-key",
];
pub(crate) const LEGACY_PROVIDER_SECRET_PREFIXES: &[&str] = &[
    "provider.anthropic-compatible.api-key",
    "provider.minimax.api-key",
];
/// 每个 provider 允许的官方/可信模型服务 host（providers.json 每项 trustedHosts 生成，
/// 小写精确匹配）。自定义端点 host 必须命中该 provider 自己的表——Provider A 的
/// Secret 不会被发往 Provider B 的官方域名（provider→origin 强绑定）。
pub(crate) const PROVIDER_TRUSTED_HOSTS: &[(&str, &[&str])] = &[
    ("generic-openai-compatible", &["api.openai.com"]),
    ("custom-openai-compatible", &[]),
    ("openai", &["api.openai.com"]),
    ("generic-anthropic-compatible", &["api.anthropic.com"]),
    ("custom-anthropic-compatible", &[]),
    ("zhipu-glm", &["open.bigmodel.cn"]),
    ("deepseek", &["api.deepseek.com"]),
    ("minimax-chat", &["api.minimaxi.com"]),
    ("ollama", &[]),
    ("gemini", &["generativelanguage.googleapis.com"]),
    ("kimi", &["api.moonshot.cn"]),
    ("kimi-coding", &["api.kimi.com"]),
    ("orcarouter", &["api.orcarouter.ai"]),
    ("opencode-go", &["opencode.ai"]),
];

/// provider 静态请求头（providers.json requestHeaders 生成）。值是**发送值**，{version}
/// 占位由 model_http 在请求期替换为应用版本（生成物保持字面量，发版不触发 digest 漂移）。
pub(crate) const PROVIDER_REQUEST_HEADERS: &[(&str, &[(&str, &str)])] =
    &[("opencode-go", &[("user-agent", "Axiom/{version}")])];

/// provider 会话头名（providers.json sessionHeader 生成）：值取请求携带的 sessionId，
/// 上游按它做路由/提示缓存亲和（缺失即 400 MissingSessionID，因此恒不省略）。
pub(crate) const PROVIDER_SESSION_HEADERS: &[(&str, &str)] =
    &[("opencode-go", "x-opencode-session")];

/// 会话头的 host 级声明（由声明了 sessionHeader 的 provider 的默认 endpoint host 与
/// trustedHosts 派生）：要求属于服务而非 provider 条目——把该服务配成自定义 provider
/// 的请求同样必须带这个头。匹配为「精确 host 或子域」。
pub(crate) const PROVIDER_SESSION_HEADER_HOSTS: &[(&str, &str)] =
    &[("opencode.ai", "x-opencode-session")];

pub(crate) const GENERATED_PROVIDER_ENTRIES: &[ProviderProfileEntry] = &[
    ProviderProfileEntry {
        provider_id: "generic-openai-compatible",
        api_format: ModelApiFormat::OpenaiCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.openai-compatible.api-key"),
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.generic-openai-compatible",
            endpoint: "https://api.openai.com/v1/chat/completions",
            model_id: "",
            timeout_ms: 60_000,
            max_output_tokens: 4_096,
            context_window: 128_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "custom-openai-compatible",
        api_format: ModelApiFormat::OpenaiCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.custom-openai-compatible.api-key"),
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.custom-openai-compatible",
            endpoint: "https://example.com/v1/chat/completions",
            model_id: "",
            timeout_ms: 60_000,
            max_output_tokens: 4_096,
            context_window: 128_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: true,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "openai",
        api_format: ModelApiFormat::OpenaiResponses,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.openai-responses.api-key"),
            required: true,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: true,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.openai",
            endpoint: "https://api.openai.com/v1/responses",
            model_id: "",
            timeout_ms: 60_000,
            max_output_tokens: 4_096,
            context_window: 128_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "generic-anthropic-compatible",
        api_format: ModelApiFormat::AnthropicCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.generic-anthropic-compatible.api-key"),
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: true,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.generic-anthropic-compatible",
            endpoint: "https://api.anthropic.com/v1/messages",
            model_id: "",
            timeout_ms: 60_000,
            max_output_tokens: 4_096,
            context_window: 128_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[
            "provider.anthropic-compatible.api-key",
            "provider.minimax.api-key",
        ],
    },
    ProviderProfileEntry {
        provider_id: "custom-anthropic-compatible",
        api_format: ModelApiFormat::AnthropicCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.custom-anthropic-compatible.api-key"),
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.custom-anthropic-compatible",
            endpoint: "https://example.com/v1/messages",
            model_id: "",
            timeout_ms: 60_000,
            max_output_tokens: 4_096,
            context_window: 128_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: true,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "zhipu-glm",
        api_format: ModelApiFormat::OpenaiCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.zhipu-glm.api-key"),
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.zhipu-glm",
            endpoint: "https://open.bigmodel.cn/api/coding/paas/v4/chat/completions",
            model_id: "glm-5.2",
            timeout_ms: 60_000,
            max_output_tokens: 64_000,
            context_window: 1_000_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "deepseek",
        api_format: ModelApiFormat::OpenaiCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.deepseek.api-key"),
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.deepseek",
            endpoint: "https://api.deepseek.com/chat/completions",
            model_id: "deepseek-flash",
            timeout_ms: 60_000,
            max_output_tokens: 4_096,
            context_window: 1_000_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "minimax-chat",
        api_format: ModelApiFormat::OpenaiCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.minimax-chat.api-key"),
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.minimax-chat",
            endpoint: "https://api.minimaxi.com/v1/chat/completions",
            model_id: "abab6.5s",
            timeout_ms: 60_000,
            max_output_tokens: 4_096,
            context_window: 128_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "ollama",
        api_format: ModelApiFormat::OpenaiCompatible,
        auth: ProviderAuth {
            kind: AuthKind::None,
            default_secret_id: None,
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.ollama",
            endpoint: "http://127.0.0.1:11434/v1/chat/completions",
            model_id: "llama3.3",
            timeout_ms: 60_000,
            max_output_tokens: 4_096,
            context_window: 128_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "gemini",
        api_format: ModelApiFormat::OpenaiCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.gemini.api-key"),
            required: true,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.gemini",
            endpoint: "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
            model_id: "gemini-2.5-flash",
            timeout_ms: 60_000,
            max_output_tokens: 8_192,
            context_window: 1_000_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "kimi",
        api_format: ModelApiFormat::OpenaiCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.kimi.api-key"),
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.kimi",
            endpoint: "https://api.moonshot.cn/v1/chat/completions",
            model_id: "kimi-k3",
            timeout_ms: 60_000,
            max_output_tokens: 32_768,
            context_window: 1_000_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "kimi-coding",
        api_format: ModelApiFormat::AnthropicCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.kimi-coding.api-key"),
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.kimi-coding",
            endpoint: "https://api.kimi.com/coding/v1/messages",
            model_id: "kimi-for-coding",
            timeout_ms: 60_000,
            max_output_tokens: 32_768,
            context_window: 262_144,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "orcarouter",
        api_format: ModelApiFormat::OpenaiCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.orcarouter.api-key"),
            required: false,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.orcarouter",
            endpoint: "https://api.orcarouter.ai/v1/chat/completions",
            model_id: "orcarouter/auto",
            timeout_ms: 60_000,
            max_output_tokens: 4_096,
            context_window: 128_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[],
        legacy_secret_id_prefixes: &[],
    },
    ProviderProfileEntry {
        provider_id: "opencode-go",
        api_format: ModelApiFormat::OpenaiCompatible,
        auth: ProviderAuth {
            kind: AuthKind::ApiKey,
            default_secret_id: Some("provider.opencode-go.api-key"),
            required: true,
        },
        supported_capabilities: ProviderCapabilities {
            tool_references: false,
            tool_search: false,
        },
        default_profile: ProviderDefaultProfile {
            profile_id: "builtin.opencode-go",
            endpoint: "https://opencode.ai/zen/go/v1/chat/completions",
            model_id: "glm-5.3",
            timeout_ms: 60_000,
            max_output_tokens: 8_192,
            context_window: 200_000,
            capabilities: ProviderCapabilities {
                tool_references: false,
                tool_search: false,
            },
        },
        allow_public_endpoints: false,
        model_wires: &[
            ProviderModelWire {
                model_id: "minimax-m3",
                api_format: ModelApiFormat::AnthropicCompatible,
                endpoint: "https://opencode.ai/zen/go/v1/messages",
            },
            ProviderModelWire {
                model_id: "minimax-m2.7",
                api_format: ModelApiFormat::AnthropicCompatible,
                endpoint: "https://opencode.ai/zen/go/v1/messages",
            },
            ProviderModelWire {
                model_id: "minimax-m2.5",
                api_format: ModelApiFormat::AnthropicCompatible,
                endpoint: "https://opencode.ai/zen/go/v1/messages",
            },
            ProviderModelWire {
                model_id: "qwen3.8-max",
                api_format: ModelApiFormat::AnthropicCompatible,
                endpoint: "https://opencode.ai/zen/go/v1/messages",
            },
            ProviderModelWire {
                model_id: "qwen3.8-flash",
                api_format: ModelApiFormat::AnthropicCompatible,
                endpoint: "https://opencode.ai/zen/go/v1/messages",
            },
            ProviderModelWire {
                model_id: "qwen3.7-max",
                api_format: ModelApiFormat::AnthropicCompatible,
                endpoint: "https://opencode.ai/zen/go/v1/messages",
            },
            ProviderModelWire {
                model_id: "qwen3.7-plus",
                api_format: ModelApiFormat::AnthropicCompatible,
                endpoint: "https://opencode.ai/zen/go/v1/messages",
            },
            ProviderModelWire {
                model_id: "qwen3.6-plus",
                api_format: ModelApiFormat::AnthropicCompatible,
                endpoint: "https://opencode.ai/zen/go/v1/messages",
            },
            ProviderModelWire {
                model_id: "grok-4.6",
                api_format: ModelApiFormat::OpenaiResponses,
                endpoint: "https://opencode.ai/zen/go/v1/responses",
            },
            ProviderModelWire {
                model_id: "gpt-5.6-luna",
                api_format: ModelApiFormat::OpenaiResponses,
                endpoint: "https://opencode.ai/zen/go/v1/responses",
            },
            ProviderModelWire {
                model_id: "muse-spark-1.3-contributor",
                api_format: ModelApiFormat::OpenaiResponses,
                endpoint: "https://opencode.ai/zen/go/v1/responses",
            },
            ProviderModelWire {
                model_id: "muse-spark-1.2-contributor",
                api_format: ModelApiFormat::OpenaiResponses,
                endpoint: "https://opencode.ai/zen/go/v1/responses",
            },
        ],
        legacy_secret_id_prefixes: &[],
    },
];
