/**
 * .pen icon 名称 → lucide-react 组件的显式映射。
 *
 * 不做运行时 kebab→Pascal 转换：lucide 新旧命名迁移（如 CircleAlert、
 * ChartColumn、Ellipsis、OctagonX、MonitorCog）存在别名陷阱，显式映射
 * 在编译期暴露拼写错误（typecheck 直接红），且保持 tree-shaking 有效。
 */
import type { LucideIcon } from 'lucide-react'
import {
  AppWindow,
  Archive,
  ArchiveRestore,
  ArrowLeft,
  ArrowUp,
  AtSign,
  BookOpen,
  Bot,
  Brain,
  Bug,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleArrowDown,
  CircleCheck,
  CirclePause,
  CirclePlus,
  CircleQuestionMark,
  ClipboardList,
  Coffee,
  Compass,
  Copy,
  Cpu,
  Download,
  Ellipsis,
  Eraser,
  ExternalLink,
  Eye,
  FileCheck,
  FileText,
  FileUp,
  FileX,
  FlaskConical,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderUp,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Globe,
  GripVertical,
  HardDrive,
  Image,
  KeyRound,
  Languages,
  Layout,
  Lightbulb,
  ListChecks,
  Loader,
  LoaderCircle,
  Lock,
  LockKeyhole,
  MessageCircleQuestionMark,
  MessageSquarePlus,
  MessageSquareText,
  Monitor,
  MonitorCog,
  MonitorSmartphone,
  OctagonX,
  Package,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pencil,
  PencilLine,
  Play,
  Plug,
  PlugZap,
  Plus,
  Power,
  PowerOff,
  QrCode,
  Recycle,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Scale,
  Send,
  Server,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Square,
  SquarePen,
  SquarePlus,
  SquareTerminal,
  Terminal,
  TextCursor,
  Trash2,
  TriangleAlert,
  Type,
  UserCheck,
  Workflow,
  Wrench,
  X,
  Zap,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  'app-window': AppWindow,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'at-sign': AtSign,
  'book-open': BookOpen,
  bot: Bot,
  brain: Brain,
  bug: Bug,
  'chart-column': ChartColumn,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-arrow-down': CircleArrowDown,
  'circle-check': CircleCheck,
  'circle-pause': CirclePause,
  'circle-plus': CirclePlus,
  'circle-question-mark': CircleQuestionMark,
  'clipboard-list': ClipboardList,
  coffee: Coffee,
  compass: Compass,
  copy: Copy,
  cpu: Cpu,
  ellipsis: Ellipsis,
  download: Download,
  eraser: Eraser,
  'external-link': ExternalLink,
  eye: Eye,
  'file-check': FileCheck,
  'file-text': FileText,
  'file-up': FileUp,
  'file-x': FileX,
  'flask-conical': FlaskConical,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  'folder-up': FolderUp,
  'git-branch': GitBranch,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  globe: Globe,
  'grip-vertical': GripVertical,
  'hard-drive': HardDrive,
  image: Image,
  'key-round': KeyRound,
  languages: Languages,
  layout: Layout,
  lightbulb: Lightbulb,
  'list-checks': ListChecks,
  loader: Loader,
  'loader-circle': LoaderCircle,
  lock: Lock,
  'lock-keyhole': LockKeyhole,
  'message-circle-question-mark': MessageCircleQuestionMark,
  'message-square-plus': MessageSquarePlus,
  'message-square-text': MessageSquareText,
  monitor: Monitor,
  'monitor-cog': MonitorCog,
  'monitor-smartphone': MonitorSmartphone,
  'octagon-x': OctagonX,
  package: Package,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  paperclip: Paperclip,
  pencil: Pencil,
  'pencil-line': PencilLine,
  play: Play,
  plug: Plug,
  'plug-zap': PlugZap,
  plus: Plus,
  power: Power,
  'power-off': PowerOff,
  'qr-code': QrCode,
  recycle: Recycle,
  'refresh-cw': RefreshCw,
  scale: Scale,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  send: Send,
  server: Server,
  settings: Settings,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  square: Square,
  'square-pen': SquarePen,
  'square-plus': SquarePlus,
  'square-terminal': SquareTerminal,
  terminal: Terminal,
  smartphone: Smartphone,
  'text-cursor': TextCursor,
  // lucide 的 PascalCase 是 Trash2，kebab 归一为 trash2，与设计稿的 trash-2 不同名。
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  type: Type,
  'user-check': UserCheck,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  zap: Zap,
}

/** 解析 icon 名：未知名称返回 undefined（渲染层降级为占位）。 */
export const resolvePenIcon = (name: string | undefined): LucideIcon | undefined =>
  name ? ICON_MAP[name] : undefined

/**
 * 懒加载兜底：静态映射未命中的名字（新稿件用了词表外的合法 lucide 图标）→
 * 动态加载完整 lucide-react 命名空间按 kebab→Pascal 查找。全量 lucide 约 1500 个
 * 图标，手工清单永远追不平模型新写的图标名——显式映射负责高频集（编译期拼写
 * 校验 + tree-shaking），兜底负责长尾（独立 chunk，只在首次 miss 时加载一次；
 * 查不到仍返回 undefined，与静态路径同口径降级为占位）。lucide 保留的旧别名
 * （AlertCircle 等）也在命名空间里，存量 .pen 稿的旧命名顺带受益。
 */
let lucideNamespace: Promise<Record<string, LucideIcon> | null> | null = null

const kebabToPascalCase = (name: string): string =>
  name
    .split('-')
    .map((part) => (part ? part.charAt(0).toUpperCase() + part.slice(1) : ''))
    .join('')

export const resolvePenIconLazy = async (name: string | undefined): Promise<LucideIcon | undefined> => {
  const direct = resolvePenIcon(name)
  if (direct) return direct
  if (!name) return undefined
  lucideNamespace ??= import('lucide-react')
    .then((namespace) => namespace as unknown as Record<string, LucideIcon>)
    .catch(() => null)
  const namespace = await lucideNamespace
  if (!namespace) return undefined
  return namespace[kebabToPascalCase(name)]
}
