// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getRuntimeInfo: () => __TAURI_INVOKE<RuntimeInfo>("get_runtime_info"),
	listAuthorizedReadFiles: () => __TAURI_INVOKE<AuthorizedReadFile[]>("list_authorized_read_files"),
	revokeAuthorizedReadFile: (path: string) => __TAURI_INVOKE<boolean>("revoke_authorized_read_file", { path }),
	/**
	 *  读取绝对路径的文本文件（工作区外 `read` 工具的唯一通道）。读取面免审批
	 *  （对齐 codex 的全盘读语义）：不要求逐文件授权，但保留与 bash 沙箱同一集合
	 *  的敏感路径 deny（凭据载体 + `~/.axiom` 数据根）——read 不得成为绕过沙箱
	 *  凭据保护的旁路。canonicalize 先于 deny 判定：symlink 置换指向 deny 目标
	 *  同样被拒；路径位于任一授权工作区内时豁免（镜像沙箱「工作区位于 deny 目录
	 *  内时跳过该目录」语义）。HOME 来源与沙箱 profile 一致（`$HOME` 环境变量），
	 *  保证两侧 deny 集合判定在同一坐标系上。
	 */
	readAuthorizedText: (path: string) => __TAURI_INVOKE<AuthorizedTextContent>("read_authorized_text", { path }),
	getAuthorizedWorkspace: () => __TAURI_INVOKE<{
	path: string,
	name: string,
	gitBranch: string | null,
} | null>("get_authorized_workspace"),
	getAuthorizedWorkspaces: () => __TAURI_INVOKE<AuthorizedWorkspace[]>("get_authorized_workspaces"),
	activateAuthorizedWorkspace: (path: string) => __TAURI_INVOKE<AuthorizedWorkspace>("activate_authorized_workspace", { path }),
	revokeWorkspace: (path: string | null) => __TAURI_INVOKE<boolean>("revoke_workspace", { path }),
};

/* Types */
export type AuthorizedReadFile = {
	path: string,
	name: string,
	sizeBytes: number,
	isDirectory: boolean,
};

export type AuthorizedTextContent = {
	file: AuthorizedReadFile,
	content: string,
};

export type AuthorizedWorkspace = {
	path: string,
	name: string,
	gitBranch: string | null,
};

export type RuntimeInfo = {
	appName: string,
	appVersion: string,
	operatingSystem: string,
	architecture: string,
};

