// @generated by scripts/generate-provider-sources.mjs — DO NOT EDIT.
//
// Provider 声明数据段（contracts/providers.json 单一来源）。只含类型与字面量，
// 不得 import 任何 Provider Runtime / Registry / CredentialRuntime。

export interface GeneratedProviderModel {
  readonly modelId: string
  readonly label: string
  readonly contextWindow: number
  readonly maxOutputTokens: number
  readonly input: readonly ('text' | 'image')[]
  readonly supportsReasoning: boolean
}

export interface GeneratedProviderCapabilities {
  readonly toolReferences: boolean
  readonly toolSearch: boolean
}

export type GeneratedProviderAuth =
  | { readonly kind: 'none' }
  | { readonly kind: 'api-key'; readonly defaultSecretId: string; readonly required: boolean }

export interface GeneratedProviderProfile {
  readonly profileId: string
  readonly endpoint: string
  readonly modelId: string
  readonly timeoutMs: number
  readonly maxOutputTokens: number
  readonly contextWindow: number
  readonly capabilities: GeneratedProviderCapabilities
}

export interface GeneratedProviderData {
  readonly id: string
  readonly label: string
  readonly apiFormat: 'openai-compatible' | 'openai-responses' | 'anthropic-compatible'
  readonly transportVersion: string
  readonly auth: GeneratedProviderAuth
  readonly supportedCapabilities: GeneratedProviderCapabilities
  readonly defaultProfile: GeneratedProviderProfile
  readonly legacySecretIdPrefixes: readonly string[]
  readonly models: readonly GeneratedProviderModel[]
}

export const PROVIDER_CONSTANTS = {
  timeoutMinMs: 1_000,
  timeoutMaxMs: 300_000,
  timeoutDefaultMs: 60_000,
  maxOutputMin: 1,
  maxOutputMax: 64_000,
  maxOutputDefault: 4_096,
  contextMin: 8_192,
  contextMax: 2_000_000,
  contextDefault: 128_000,
  identifierMaxBytes: 128,
  endpointMaxBytes: 4_096,
  modelIdMaxBytes: 256,
} as const

export const PROVIDER_IDS = ['generic-openai-compatible', 'custom-openai-compatible', 'openai', 'generic-anthropic-compatible', 'custom-anthropic-compatible', 'zhipu-glm', 'deepseek', 'minimax-chat', 'ollama', 'gemini', 'kimi', 'kimi-coding', 'orcarouter'] as const

export const PROVIDER_DATA: readonly GeneratedProviderData[] = [
  {
    id: 'generic-openai-compatible',
    label: 'OpenAI Compatible',
    apiFormat: 'openai-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.openai-compatible.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.generic-openai-compatible',
      endpoint: 'https://api.openai.com/v1/chat/completions',
      modelId: '',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [],
  },
  {
    id: 'custom-openai-compatible',
    label: '自定义（OpenAI）',
    apiFormat: 'openai-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.custom-openai-compatible.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.custom-openai-compatible',
      endpoint: 'https://example.com/v1/chat/completions',
      modelId: '',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [],
  },
  {
    id: 'openai',
    label: 'OpenAI Responses',
    apiFormat: 'openai-responses',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.openai-responses.api-key',
      required: true,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: true,
    },
    defaultProfile: {
      profileId: 'builtin.openai',
      endpoint: 'https://api.openai.com/v1/responses',
      modelId: '',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [],
  },
  {
    id: 'generic-anthropic-compatible',
    label: 'Anthropic Compatible',
    apiFormat: 'anthropic-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.generic-anthropic-compatible.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: true,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.generic-anthropic-compatible',
      endpoint: 'https://api.anthropic.com/v1/messages',
      modelId: '',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: ['provider.anthropic-compatible.api-key', 'provider.minimax.api-key'],
    models: [],
  },
  {
    id: 'custom-anthropic-compatible',
    label: '自定义（Anthropic）',
    apiFormat: 'anthropic-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.custom-anthropic-compatible.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.custom-anthropic-compatible',
      endpoint: 'https://example.com/v1/messages',
      modelId: '',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [],
  },
  {
    id: 'zhipu-glm',
    label: 'GLM',
    apiFormat: 'openai-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.zhipu-glm.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.zhipu-glm',
      endpoint: 'https://open.bigmodel.cn/api/coding/paas/v4/chat/completions',
      modelId: 'glm-5.2',
      timeoutMs: 60_000,
      maxOutputTokens: 64_000,
      contextWindow: 1_000_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'glm-5.2',
    label: 'GLM-5.2',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-4.6',
    label: 'GLM-4.6',
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-4.5',
    label: 'GLM-4.5',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-4.5-air',
    label: 'GLM-4.5-Air',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-4-flash',
    label: 'GLM-4-Flash',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: false,
  }],
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    apiFormat: 'openai-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.deepseek.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.deepseek',
      endpoint: 'https://api.deepseek.com/chat/completions',
      modelId: 'deepseek-v4-flash',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 1_000_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'deepseek-v4-flash',
    label: 'DeepSeek V4 Flash',
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'deepseek-v4-pro',
    label: 'DeepSeek V4 Pro',
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  }],
  },
  {
    id: 'minimax-chat',
    label: 'MiniMax',
    apiFormat: 'openai-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.minimax-chat.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.minimax-chat',
      endpoint: 'https://api.minimaxi.com/v1/chat/completions',
      modelId: 'abab6.5s',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'abab6.5s',
    label: 'MiniMax abab6.5s',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'minimax-text-01',
    label: 'MiniMax Text-01',
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  }],
  },
  {
    id: 'ollama',
    label: 'Ollama',
    apiFormat: 'openai-compatible',
    transportVersion: '6',
    auth: { kind: 'none' },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.ollama',
      endpoint: 'http://127.0.0.1:11434/v1/chat/completions',
      modelId: 'llama3.3',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'llama3.3',
    label: 'Llama 3.3',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'qwen3',
    label: 'Qwen 3',
    contextWindow: 256_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'deepseek-r1',
    label: 'DeepSeek R1',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'gemma3',
    label: 'Gemma 3',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: ['text', 'image'],
    supportsReasoning: false,
  },
    {
    modelId: 'phi4',
    label: 'Phi-4',
    contextWindow: 16_384,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'mistral',
    label: 'Mistral',
    contextWindow: 32_768,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: false,
  }],
  },
  {
    id: 'gemini',
    label: 'Google Gemini',
    apiFormat: 'openai-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.gemini.api-key',
      required: true,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.gemini',
      endpoint: 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
      modelId: 'gemini-2.5-flash',
      timeoutMs: 60_000,
      maxOutputTokens: 8_192,
      contextWindow: 1_000_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    contextWindow: 1_000_000,
    maxOutputTokens: 65_536,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    contextWindow: 1_000_000,
    maxOutputTokens: 65_536,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'gemini-2.5-flash-lite',
    label: 'Gemini 2.5 Flash-Lite',
    contextWindow: 1_000_000,
    maxOutputTokens: 65_536,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'gemini-2.0-flash',
    label: 'Gemini 2.0 Flash',
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: false,
  }],
  },
  {
    id: 'kimi',
    label: 'Kimi',
    apiFormat: 'openai-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.kimi.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.kimi',
      endpoint: 'https://api.moonshot.cn/v1/chat/completions',
      modelId: 'kimi-k3',
      timeoutMs: 60_000,
      maxOutputTokens: 32_768,
      contextWindow: 1_000_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'kimi-k3',
    label: 'Kimi K3',
    contextWindow: 1_000_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'kimi-k2.7-code-highspeed',
    label: 'Kimi K2.7 Code',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'kimi-k2.6',
    label: 'Kimi K2.6',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  }],
  },
  {
    id: 'kimi-coding',
    label: 'Kimi Coding',
    apiFormat: 'anthropic-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.kimi-coding.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.kimi-coding',
      endpoint: 'https://api.kimi.com/coding/v1/messages',
      modelId: 'kimi-for-coding',
      timeoutMs: 60_000,
      maxOutputTokens: 32_768,
      contextWindow: 262_144,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'kimi-for-coding',
    label: 'Kimi For Coding',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text', 'image'],
    supportsReasoning: true,
  },
    {
    modelId: 'kimi-for-coding-highspeed',
    label: 'Kimi For Coding HighSpeed',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text', 'image'],
    supportsReasoning: true,
  }],
  },
  {
    id: 'orcarouter',
    label: 'OrcaRouter',
    apiFormat: 'openai-compatible',
    transportVersion: '6',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.orcarouter.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.orcarouter',
      endpoint: 'https://api.orcarouter.ai/v1/chat/completions',
      modelId: 'orcarouter/auto',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'orcarouter/auto',
    label: 'OrcaRouter Auto（自动路由）',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'openai/gpt-4o-mini',
    label: 'OpenAI GPT-4o mini (via OrcaRouter)',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'anthropic/claude-sonnet-4.6',
    label: 'Anthropic Claude Sonnet 4.6 (via OrcaRouter)',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'google/gemini-2.5-flash',
    label: 'Google Gemini 2.5 Flash (via OrcaRouter)',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'deepseek/deepseek-chat',
    label: 'DeepSeek Chat (via OrcaRouter)',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'z-ai/glm-5',
    label: 'Z.ai GLM-5 (via OrcaRouter)',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: ['text'],
    supportsReasoning: true,
  }],
  },
]
