// @generated by scripts/generate-provider-sources.mjs — DO NOT EDIT.
//
// Provider 声明数据段（contracts/providers.json 单一来源）。只含类型与字面量，
// 不得 import 任何 Provider Runtime / Registry / CredentialRuntime。

export interface GeneratedProviderModel {
  readonly modelId: string
  readonly label: string
  readonly contextWindow: number
  readonly maxOutputTokens: number
  readonly input: readonly ('text' | 'image')[]
  readonly supportsReasoning: boolean
  /**
   * 模型级 wire（多协议网关专用）：该模型不走 provider 默认 apiFormat/endpoint，而是走
   * 自己的协议与路径（如 OpenCode Go 的 /responses、/messages）。缺省时用 provider 默认。
   */
  readonly wire?: GeneratedProviderWire
}

export interface GeneratedProviderWire {
  readonly apiFormat: 'openai-compatible' | 'openai-responses' | 'anthropic-compatible'
  readonly endpoint: string
}

export interface GeneratedProviderCapabilities {
  readonly toolReferences: boolean
  readonly toolSearch: boolean
}

export type GeneratedProviderAuth =
  | { readonly kind: 'none' }
  | { readonly kind: 'api-key'; readonly defaultSecretId: string; readonly required: boolean }

export interface GeneratedProviderProfile {
  readonly profileId: string
  readonly endpoint: string
  readonly modelId: string
  readonly timeoutMs: number
  readonly maxOutputTokens: number
  readonly contextWindow: number
  readonly capabilities: GeneratedProviderCapabilities
}

export interface GeneratedProviderData {
  readonly id: string
  readonly label: string
  readonly apiFormat: 'openai-compatible' | 'openai-responses' | 'anthropic-compatible'
  readonly transportVersion: string
  readonly auth: GeneratedProviderAuth
  /**
   * 静态请求头（发送值，{version} 占位由 Rust 侧替换为应用版本）；TS 不消费，
   * 只为与 Rust 生成表保持单一数据源与可审计性。
   */
  readonly requestHeaders?: Readonly<Record<string, string>>
  /** 会话头名：值取请求携带的 sessionId（Rust 侧注入）。 */
  readonly sessionHeader?: string
  /**
   * 官网地址（UI-only 展示字段，不进 Rust 表）：设置页把订阅型 provider 的官方入口与
   * 邀请/优惠链接呈现给用户。生成期已校验 https 且无内嵌凭据。
   */
  readonly website?: string
  /** 邀请/优惠链接（UI-only）：与官网并列展示，供用户订阅时获得优惠。 */
  readonly inviteUrl?: string
  readonly supportedCapabilities: GeneratedProviderCapabilities
  readonly defaultProfile: GeneratedProviderProfile
  readonly legacySecretIdPrefixes: readonly string[]
  readonly models: readonly GeneratedProviderModel[]
}

export const PROVIDER_CONSTANTS = {
  timeoutMinMs: 1_000,
  timeoutMaxMs: 300_000,
  timeoutDefaultMs: 60_000,
  maxOutputMin: 1,
  maxOutputMax: 512_000,
  maxOutputDefault: 4_096,
  contextMin: 8_192,
  contextMax: 2_000_000,
  contextDefault: 128_000,
  identifierMaxBytes: 128,
  endpointMaxBytes: 4_096,
  modelIdMaxBytes: 256,
} as const

export const PROVIDER_IDS = ['generic-openai-compatible', 'custom-openai-compatible', 'openai', 'generic-anthropic-compatible', 'custom-anthropic-compatible', 'zhipu-glm', 'deepseek', 'minimax-chat', 'ollama', 'gemini', 'kimi', 'kimi-coding', 'orcarouter', 'opencode-go'] as const

export const PROVIDER_DATA: readonly GeneratedProviderData[] = [
  {
    id: 'generic-openai-compatible',
    label: 'OpenAI Compatible',
    apiFormat: 'openai-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.openai-compatible.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.generic-openai-compatible',
      endpoint: 'https://api.openai.com/v1/chat/completions',
      modelId: '',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [],
  },
  {
    id: 'custom-openai-compatible',
    label: '自定义（OpenAI）',
    apiFormat: 'openai-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.custom-openai-compatible.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.custom-openai-compatible',
      endpoint: 'https://example.com/v1/chat/completions',
      modelId: '',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [],
  },
  {
    id: 'openai',
    label: 'OpenAI Responses',
    apiFormat: 'openai-responses',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.openai-responses.api-key',
      required: true,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: true,
    },
    defaultProfile: {
      profileId: 'builtin.openai',
      endpoint: 'https://api.openai.com/v1/responses',
      modelId: '',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [],
  },
  {
    id: 'generic-anthropic-compatible',
    label: 'Anthropic Compatible',
    apiFormat: 'anthropic-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.generic-anthropic-compatible.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: true,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.generic-anthropic-compatible',
      endpoint: 'https://api.anthropic.com/v1/messages',
      modelId: '',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: ['provider.anthropic-compatible.api-key', 'provider.minimax.api-key'],
    models: [],
  },
  {
    id: 'custom-anthropic-compatible',
    label: '自定义（Anthropic）',
    apiFormat: 'anthropic-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.custom-anthropic-compatible.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.custom-anthropic-compatible',
      endpoint: 'https://example.com/v1/messages',
      modelId: '',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [],
  },
  {
    id: 'zhipu-glm',
    label: 'GLM',
    apiFormat: 'openai-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.zhipu-glm.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.zhipu-glm',
      endpoint: 'https://open.bigmodel.cn/api/coding/paas/v4/chat/completions',
      modelId: 'glm-5.2',
      timeoutMs: 60_000,
      maxOutputTokens: 64_000,
      contextWindow: 1_000_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'glm-5.2',
    label: 'GLM-5.2',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-5.3-flash',
    label: 'GLM-5.3-Flash',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    input: ['text', 'image'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-4.6',
    label: 'GLM-4.6',
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-4.5',
    label: 'GLM-4.5',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-4.5-air',
    label: 'GLM-4.5-Air',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-4-flash',
    label: 'GLM-4-Flash',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: false,
  }],
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    apiFormat: 'openai-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.deepseek.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.deepseek',
      endpoint: 'https://api.deepseek.com/chat/completions',
      modelId: 'deepseek-flash',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 1_000_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'deepseek-flash',
    label: 'DeepSeek Flash',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    input: ['text', 'image'],
    supportsReasoning: true,
  },
    {
    modelId: 'deepseek-v4-flash',
    label: 'DeepSeek V4 Flash',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    input: ['text', 'image'],
    supportsReasoning: true,
  },
    {
    modelId: 'deepseek-v4-pro',
    label: 'DeepSeek V4 Pro',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    input: ['text'],
    supportsReasoning: true,
  }],
  },
  {
    id: 'minimax-chat',
    label: 'MiniMax',
    apiFormat: 'openai-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.minimax-chat.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.minimax-chat',
      endpoint: 'https://api.minimaxi.com/v1/chat/completions',
      modelId: 'abab6.5s',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'minimax-m3',
    label: 'MiniMax M3',
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    input: ['text', 'image'],
    supportsReasoning: true,
  },
    {
    modelId: 'abab6.5s',
    label: 'MiniMax abab6.5s',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'minimax-text-01',
    label: 'MiniMax Text-01',
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  }],
  },
  {
    id: 'ollama',
    label: 'Ollama',
    apiFormat: 'openai-compatible',
    transportVersion: '10',
    auth: { kind: 'none' },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.ollama',
      endpoint: 'http://127.0.0.1:11434/v1/chat/completions',
      modelId: 'llama3.3',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'llama3.3',
    label: 'Llama 3.3',
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'qwen3',
    label: 'Qwen 3',
    contextWindow: 256_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'deepseek-r1',
    label: 'DeepSeek R1',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'gemma3',
    label: 'Gemma 3',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: ['text', 'image'],
    supportsReasoning: false,
  },
    {
    modelId: 'phi4',
    label: 'Phi-4',
    contextWindow: 16_384,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'mistral',
    label: 'Mistral',
    contextWindow: 32_768,
    maxOutputTokens: 4_096,
    input: ['text'],
    supportsReasoning: false,
  }],
  },
  {
    id: 'gemini',
    label: 'Google Gemini',
    apiFormat: 'openai-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.gemini.api-key',
      required: true,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.gemini',
      endpoint: 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
      modelId: 'gemini-2.5-flash',
      timeoutMs: 60_000,
      maxOutputTokens: 8_192,
      contextWindow: 1_000_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    contextWindow: 1_000_000,
    maxOutputTokens: 65_536,
    input: ['text', 'image'],
    supportsReasoning: true,
  },
    {
    modelId: 'gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    contextWindow: 1_000_000,
    maxOutputTokens: 65_536,
    input: ['text', 'image'],
    supportsReasoning: true,
  },
    {
    modelId: 'gemini-2.5-flash-lite',
    label: 'Gemini 2.5 Flash-Lite',
    contextWindow: 1_000_000,
    maxOutputTokens: 65_536,
    input: ['text', 'image'],
    supportsReasoning: false,
  },
    {
    modelId: 'gemini-2.0-flash',
    label: 'Gemini 2.0 Flash',
    contextWindow: 1_000_000,
    maxOutputTokens: 8_192,
    input: ['text', 'image'],
    supportsReasoning: false,
  }],
  },
  {
    id: 'kimi',
    label: 'Kimi',
    apiFormat: 'openai-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.kimi.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.kimi',
      endpoint: 'https://api.moonshot.cn/v1/chat/completions',
      modelId: 'kimi-k3',
      timeoutMs: 60_000,
      maxOutputTokens: 32_768,
      contextWindow: 1_000_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'kimi-k3',
    label: 'Kimi K3',
    contextWindow: 1_000_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'kimi-k2.7-code-highspeed',
    label: 'Kimi K2.7 Code',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'kimi-k2.6',
    label: 'Kimi K2.6',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  }],
  },
  {
    id: 'kimi-coding',
    label: 'Kimi Coding',
    apiFormat: 'anthropic-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.kimi-coding.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.kimi-coding',
      endpoint: 'https://api.kimi.com/coding/v1/messages',
      modelId: 'kimi-for-coding',
      timeoutMs: 60_000,
      maxOutputTokens: 32_768,
      contextWindow: 262_144,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'kimi-for-coding',
    label: 'Kimi For Coding',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text', 'image'],
    supportsReasoning: true,
  },
    {
    modelId: 'kimi-for-coding-highspeed',
    label: 'Kimi For Coding HighSpeed',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text', 'image'],
    supportsReasoning: true,
  }],
  },
  {
    id: 'orcarouter',
    label: 'OrcaRouter',
    apiFormat: 'openai-compatible',
    transportVersion: '10',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.orcarouter.api-key',
      required: false,
    },
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.orcarouter',
      endpoint: 'https://api.orcarouter.ai/v1/chat/completions',
      modelId: 'orcarouter/auto',
      timeoutMs: 60_000,
      maxOutputTokens: 4_096,
      contextWindow: 128_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'orcarouter/auto',
    label: 'OrcaRouter Auto（自动路由）',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'openai/gpt-4o-mini',
    label: 'OpenAI GPT-4o mini (via OrcaRouter)',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'anthropic/claude-sonnet-4.6',
    label: 'Anthropic Claude Sonnet 4.6 (via OrcaRouter)',
    contextWindow: 200_000,
    maxOutputTokens: 32_000,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'google/gemini-2.5-flash',
    label: 'Google Gemini 2.5 Flash (via OrcaRouter)',
    contextWindow: 1_000_000,
    maxOutputTokens: 64_000,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'deepseek/deepseek-chat',
    label: 'DeepSeek Chat (via OrcaRouter)',
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'z-ai/glm-5',
    label: 'Z.ai GLM-5 (via OrcaRouter)',
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: ['text'],
    supportsReasoning: true,
  }],
  },
  {
    id: 'opencode-go',
    label: 'OpenCode Go',
    apiFormat: 'openai-compatible',
    transportVersion: '2',
    auth: {
      kind: 'api-key',
      defaultSecretId: 'provider.opencode-go.api-key',
      required: true,
    },
    requestHeaders: { 'user-agent': 'Axiom/{version}' },
    sessionHeader: 'x-opencode-session',
    website: 'https://opencode.ai/go',
    inviteUrl: 'https://opencode.ai/go?ref=QQ1BKKXRTV',
    supportedCapabilities: {
      toolReferences: false,
      toolSearch: false,
    },
    defaultProfile: {
      profileId: 'builtin.opencode-go',
      endpoint: 'https://opencode.ai/zen/go/v1/chat/completions',
      modelId: 'glm-5.3',
      timeoutMs: 60_000,
      maxOutputTokens: 8_192,
      contextWindow: 200_000,
      capabilities: {
        toolReferences: false,
        toolSearch: false,
      },
    },
    legacySecretIdPrefixes: [],
    models: [{
    modelId: 'glm-5.3',
    label: 'GLM-5.3 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-5.3-flash',
    label: 'GLM-5.3 Flash (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-5.2',
    label: 'GLM-5.2 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'glm-5.1',
    label: 'GLM-5.1 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'kimi-k3',
    label: 'Kimi K3 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'kimi-k2.7-code',
    label: 'Kimi K2.7 Code (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'kimi-k2.6',
    label: 'Kimi K2.6 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'longcat-2.0',
    label: 'LongCat-2.0 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 16_384,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'deepseek-v4-pro',
    label: 'DeepSeek V4 Pro (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'deepseek-v4-flash',
    label: 'DeepSeek V4 Flash (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'deepseek-v4.1-flash',
    label: 'DeepSeek V4.1 Flash (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'deepseek-v4-flash-vision-exp',
    label: 'DeepSeek V4 Flash Vision Exp (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    input: ['text', 'image'],
    supportsReasoning: true,
  },
    {
    modelId: 'mimo-v2.5',
    label: 'MiMo V2.5 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 16_384,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'mimo-v2.5-pro',
    label: 'MiMo V2.5 Pro (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 16_384,
    input: ['text'],
    supportsReasoning: true,
  },
    {
    modelId: 'hy4-preview',
    label: 'Hy4 Preview (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 16_384,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'hy3',
    label: 'Hy3 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 16_384,
    input: ['text'],
    supportsReasoning: false,
  },
    {
    modelId: 'minimax-m3',
    label: 'MiniMax M3 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
    wire: {
      apiFormat: 'anthropic-compatible',
      endpoint: 'https://opencode.ai/zen/go/v1/messages',
    },
  },
    {
    modelId: 'minimax-m2.7',
    label: 'MiniMax M2.7 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
    wire: {
      apiFormat: 'anthropic-compatible',
      endpoint: 'https://opencode.ai/zen/go/v1/messages',
    },
  },
    {
    modelId: 'minimax-m2.5',
    label: 'MiniMax M2.5 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
    wire: {
      apiFormat: 'anthropic-compatible',
      endpoint: 'https://opencode.ai/zen/go/v1/messages',
    },
  },
    {
    modelId: 'qwen3.8-max',
    label: 'Qwen3.8 Max (via OpenCode Go)',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
    wire: {
      apiFormat: 'anthropic-compatible',
      endpoint: 'https://opencode.ai/zen/go/v1/messages',
    },
  },
    {
    modelId: 'qwen3.8-flash',
    label: 'Qwen3.8 Flash (via OpenCode Go)',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
    wire: {
      apiFormat: 'anthropic-compatible',
      endpoint: 'https://opencode.ai/zen/go/v1/messages',
    },
  },
    {
    modelId: 'qwen3.7-max',
    label: 'Qwen3.7 Max (via OpenCode Go)',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
    wire: {
      apiFormat: 'anthropic-compatible',
      endpoint: 'https://opencode.ai/zen/go/v1/messages',
    },
  },
    {
    modelId: 'qwen3.7-plus',
    label: 'Qwen3.7 Plus (via OpenCode Go)',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
    wire: {
      apiFormat: 'anthropic-compatible',
      endpoint: 'https://opencode.ai/zen/go/v1/messages',
    },
  },
    {
    modelId: 'qwen3.6-plus',
    label: 'Qwen3.6 Plus (via OpenCode Go)',
    contextWindow: 262_144,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
    wire: {
      apiFormat: 'anthropic-compatible',
      endpoint: 'https://opencode.ai/zen/go/v1/messages',
    },
  },
    {
    modelId: 'grok-4.6',
    label: 'Grok 4.6 (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
    wire: {
      apiFormat: 'openai-responses',
      endpoint: 'https://opencode.ai/zen/go/v1/responses',
    },
  },
    {
    modelId: 'gpt-5.6-luna',
    label: 'GPT 5.6 Luna (via OpenCode Go)',
    contextWindow: 272_000,
    maxOutputTokens: 32_768,
    input: ['text'],
    supportsReasoning: true,
    wire: {
      apiFormat: 'openai-responses',
      endpoint: 'https://opencode.ai/zen/go/v1/responses',
    },
  },
    {
    modelId: 'muse-spark-1.3-contributor',
    label: 'Muse Spark 1.3 Contributor (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: false,
    wire: {
      apiFormat: 'openai-responses',
      endpoint: 'https://opencode.ai/zen/go/v1/responses',
    },
  },
    {
    modelId: 'muse-spark-1.2-contributor',
    label: 'Muse Spark 1.2 Contributor (via OpenCode Go)',
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
    input: ['text'],
    supportsReasoning: false,
    wire: {
      apiFormat: 'openai-responses',
      endpoint: 'https://opencode.ai/zen/go/v1/responses',
    },
  }],
  },
]
